# Generated by Django 6.0 on 2025-12-17 08:57

from django.db import migrations


def add_admin_column(apps, schema_editor):
    """Add is_admin column to user_profiles table"""
    schema_editor.execute("""
        ALTER TABLE user_profiles 
        ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE
    """)
    
    # Make the first user with PIN '1111' an admin for VR-DEVICE-001
    schema_editor.execute("""
        UPDATE user_profiles up
        SET is_admin = TRUE
        FROM users u
        WHERE up.user_id = u.id 
        AND u.pin = '1111'
        AND u.tenant_id = (SELECT id FROM tenants WHERE device_id = 'VR-DEVICE-001')
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_admin_column, migrations.RunPython.noop),
    ]
