# Generated by Django 5.2.6 on 2025-12-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_admin_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_tenant_pin',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_users_tenant_pin',
            old_name='users_tenant__b350cf_idx',
        ),
        migrations.AddField(
            model_name='tenant',
            name='admin_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='device_id',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.tenant'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant', 'pin'), name='users_tenant_id_pin_key'),
        ),
    ]
